### ISSUE TITLE
move conf dir inside src/main/resources

### ISSUE THREAD

**Issue by mfirry** [frroliveira/metamorphic#1]
Usually _things_ that are not `code` will be found inside `src/main/resources` in a standard sbt project.
I was wondering if that's possible here.

**Comment by frroliveira** [comment]
I tried that but `sbt` only adds resources to classpath after compilation. As the config file is needed in compile time, I'm creating that dummy dependency so I can access it.

**Comment by mfirry** [comment]
Alright I see. You can close this then. Thanks!
